name: pull-request
on:
  pull_request:
    types: [opened, labeled, unlabeled]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign PR
        uses: li-sumup/actions-assigner@v1.0.1
