name: pull-request
on:
  pull_request:
    types: [opened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      # - uses: li-sumup/actions-assigner@v1
      - uses: delivery-much/actions-assigner@v1
